/**
 * مصدر حقيقة واحد لكل مفاتيح الصلاحيات في النظام.
 * يُستخدم للبذور، وAPI، وتصدير المرجع.
 */
export type PermissionCatalogEntry = {
  /** مفتاح فريد بصيغة namespace:verb */
  key: string;
  /** تجميع في الواجهة */
  module: string;
  moduleLabelAr: string;
  labelAr: string;
  labelEn: string;
  descriptionAr: string;
};

export const PERMISSION_MODULES_ORDER = [
  "dashboard",
  "orders",
  "daily",
  "projects",
  "planning",
  "analytics",
  "equipment",
  "reference",
  "factory_hub",
  "directory",
  "integration",
  "audit",
  "admin",
] as const;

export const PERMISSION_CATALOG: PermissionCatalogEntry[] = [
  {
    key: "dashboard:view",
    module: "dashboard",
    moduleLabelAr: "لوحة التحكم",
    labelAr: "عرض لوحة التحكم",
    labelEn: "View dashboard",
    descriptionAr: "الوصول للصفحة الرئيسية والملخصات.",
  },
  {
    key: "dashboard:widgets",
    module: "dashboard",
    moduleLabelAr: "لوحة التحكم",
    labelAr: "تخصيص عناصر اللوحة",
    labelEn: "Customize dashboard widgets",
    descriptionAr: "إظهار/إخفاء بطاقات وروابط سريعة على لوحة التحكم.",
  },
  {
    key: "orders:metal:view",
    module: "orders",
    moduleLabelAr: "أوامر الإنتاج",
    labelAr: "عرض أوامر المعدن",
    labelEn: "View metal orders",
    descriptionAr: "صفحة أوامر مصنع المعادن.",
  },
  {
    key: "orders:metal:write",
    module: "orders",
    moduleLabelAr: "أوامر الإنتاج",
    labelAr: "تعديل أوامر المعدن",
    labelEn: "Edit metal orders",
    descriptionAr: "إنشاء وتعديل وحذف أوامر المعدن.",
  },
  {
    key: "orders:wood:view",
    module: "orders",
    moduleLabelAr: "أوامر الإنتاج",
    labelAr: "عرض أوامر الخشب",
    labelEn: "View wood orders",
    descriptionAr: "صفحة Kanban/جدول أوامر الخشب.",
  },
  {
    key: "orders:wood:write",
    module: "orders",
    moduleLabelAr: "أوامر الإنتاج",
    labelAr: "تعديل أوامر الخشب",
    labelEn: "Edit wood orders",
    descriptionAr: "تحديث المراحل والكميات وأوامر الخشب.",
  },
  {
    key: "daily:metal:view",
    module: "daily",
    moduleLabelAr: "الإنتاج اليومي",
    labelAr: "عرض اليومية — معدن",
    labelEn: "View daily production metal",
    descriptionAr: "سجل الإنتاج اليومي لمصنع المعادن.",
  },
  {
    key: "daily:metal:write",
    module: "daily",
    moduleLabelAr: "الإنتاج اليومي",
    labelAr: "إدخال اليومية — معدن",
    labelEn: "Enter daily production metal",
    descriptionAr: "حفظ وتعديل سجلات اليومية للمعدن.",
  },
  {
    key: "daily:wood:view",
    module: "daily",
    moduleLabelAr: "الإنتاج اليومي",
    labelAr: "عرض اليومية — خشب",
    labelEn: "View daily production wood",
    descriptionAr: "سجل الإنتاج اليومي لمصنع الأخشاب.",
  },
  {
    key: "daily:wood:write",
    module: "daily",
    moduleLabelAr: "الإنتاج اليومي",
    labelAr: "إدخال اليومية — خشب",
    labelEn: "Enter daily production wood",
    descriptionAr: "حفظ وتعديل سجلات اليومية للخشب.",
  },
  {
    key: "production:hub:view",
    module: "orders",
    moduleLabelAr: "أوامر الإنتاج",
    labelAr: "عرض مركز الإنتاج",
    labelEn: "View production hub",
    descriptionAr: "تبويبات أوامر وإنتاج يومي للمصانع.",
  },
  {
    key: "workforce:view",
    module: "directory",
    moduleLabelAr: "الدليل التنظيمي",
    labelAr: "عرض القوى العاملة",
    labelEn: "View workforce",
    descriptionAr: "صفحة القوى العاملة والتوزيع.",
  },
  {
    key: "projects:hub:view",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "عرض مركز المشاريع",
    labelEn: "View projects hub",
    descriptionAr: "لوحة المشاريع المشتركة وإنشاء الأوامر.",
  },
  {
    key: "projects:joint:view",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "عرض المشاريع المشتركة",
    labelEn: "View joint projects",
    descriptionAr: "قائمة المشاريع المشتركة.",
  },
  {
    key: "projects:joint:write",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "تعديل المشاريع المشتركة",
    labelEn: "Edit joint projects",
    descriptionAr: "إنشاء وتعديل المشاريع المشتركة.",
  },
  {
    key: "projects:new:view",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "عرض معالج مشروع جديد",
    labelEn: "View new project wizard",
    descriptionAr: "الوصول لصفحة مشروع جديد.",
  },
  {
    key: "projects:new:write",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "إنشاء وحفظ مشروع جديد",
    labelEn: "Create new project",
    descriptionAr: "ملء وحفظ بيانات مشروع جديد.",
  },
  {
    key: "projects:wo_analysis:view",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "عرض تحليل أوامر الشغل",
    labelEn: "View WO analysis",
    descriptionAr: "صفحة تحليل أوامر الشغل.",
  },
  {
    key: "projects:wo_analysis:write",
    module: "projects",
    moduleLabelAr: "المشاريع",
    labelAr: "تعديل جلسات التحليل",
    labelEn: "Edit WO analysis sessions",
    descriptionAr: "حفظ جلسات ونتائج التحليل.",
  },
  {
    key: "planning:view",
    module: "planning",
    moduleLabelAr: "التخطيط والجدولة",
    labelAr: "عرض التخطيط وKPI",
    labelEn: "View planning KPIs",
    descriptionAr: "صفحة التخطيط والمؤشرات الدورية.",
  },
  {
    key: "planning:write",
    module: "planning",
    moduleLabelAr: "التخطيط والجدولة",
    labelAr: "تعديل أهداف التخطيط",
    labelEn: "Edit planning targets",
    descriptionAr: "تحديث القيم والأهداف في لوحة التخطيط.",
  },
  {
    key: "analytics:multi:view",
    module: "analytics",
    moduleLabelAr: "التحليلات",
    labelAr: "عرض تحليلات متعددة المصانع",
    labelEn: "View multi-factory analytics",
    descriptionAr: "لوحة التحليلات الموحدة.",
  },
  {
    key: "analytics:wood:view",
    module: "analytics",
    moduleLabelAr: "التحليلات",
    labelAr: "عرض تحليلات الخشب",
    labelEn: "View wood analytics",
    descriptionAr: "رسوم وبيانات مصنع الأخشاب.",
  },
  {
    key: "analytics:metal:view",
    module: "analytics",
    moduleLabelAr: "التحليلات",
    labelAr: "عرض تحليلات المعادن",
    labelEn: "View metal analytics",
    descriptionAr: "رسوم وبيانات مصنع المعادن.",
  },
  {
    key: "analytics:export",
    module: "analytics",
    moduleLabelAr: "التحليلات",
    labelAr: "تصدير تقارير التحليلات",
    labelEn: "Export analytics",
    descriptionAr: "تصدير CSV/Excel من شاشات التحليلات.",
  },
  {
    key: "project_analytics:view",
    module: "analytics",
    moduleLabelAr: "التحليلات",
    labelAr: "عرض تحليلات المشاريع",
    labelEn: "View project analytics",
    descriptionAr: "صفحة تحليلات المشاريع.",
  },
  {
    key: "equipment:view",
    module: "equipment",
    moduleLabelAr: "المعدات",
    labelAr: "عرض سجل المعدات",
    labelEn: "View equipment registry",
    descriptionAr: "قراءة سجل المعدات والماكينات.",
  },
  {
    key: "equipment:write",
    module: "equipment",
    moduleLabelAr: "المعدات",
    labelAr: "تعديل سجل المعدات",
    labelEn: "Edit equipment registry",
    descriptionAr: "إضافة وتعديل بيانات المعدات عند توفر واجهات الكتابة.",
  },
  {
    key: "entity_notes:read",
    module: "reference",
    moduleLabelAr: "المرجع والبيانات",
    labelAr: "عرض الملاحظات على الكيانات",
    labelEn: "View entity notes",
    descriptionAr: "قراءة سجل الملاحظات المرتبطة بالموظفين والأوامر وغيرها.",
  },
  {
    key: "entity_notes:write",
    module: "reference",
    moduleLabelAr: "المرجع والبيانات",
    labelAr: "كتابة ملاحظات على الكيانات",
    labelEn: "Create and edit entity notes",
    descriptionAr: "إضافة وتعديل وحذف الملاحظات على الكيانات.",
  },
  {
    key: "about:view",
    module: "reference",
    moduleLabelAr: "حول النظام والمرجع",
    labelAr: "عرض حول النظام والتدريب",
    labelEn: "View about & training",
    descriptionAr: "صفحة التعريف والوثائق المرجعية.",
  },
  {
    key: "about:write",
    module: "reference",
    moduleLabelAr: "حول النظام والمرجع",
    labelAr: "تعديل محتوى مرجعي",
    labelEn: "Edit reference content",
    descriptionAr: "تحرير محتوى مرجعي مستقبلًا.",
  },
  {
    key: "factory_hub:wood:read",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "قراءة أوامر الخشب في Hub",
    labelEn: "Read wood orders hub",
    descriptionAr: "قراءة حزم أوامر الخشب من الطبقة الموحدة.",
  },
  {
    key: "factory_hub:wood:write",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "كتابة أوامر الخشب في Hub",
    labelEn: "Write wood orders hub",
    descriptionAr: "مزامنة وتعديل أوامر الخشب في Hub.",
  },
  {
    key: "factory_hub:reference:read",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "قراءة اللقطات المرجعية",
    labelEn: "Read reference snapshots",
    descriptionAr: "قراءة لقطات السعة والموظفين وغيرها.",
  },
  {
    key: "factory_hub:reference:write",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "كتابة اللقطات المرجعية",
    labelEn: "Write reference snapshots",
    descriptionAr: "تحديث بيانات مرجعية في Hub.",
  },
  {
    key: "factory_hub:analysis:read",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "قراءة تحليل أوامر الشغل (Hub)",
    labelEn: "Read WO analysis hub",
    descriptionAr: "قراءة جلسات التحليل المخزنة.",
  },
  {
    key: "factory_hub:analysis:write",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "كتابة تحليل أوامر الشغل (Hub)",
    labelEn: "Write WO analysis hub",
    descriptionAr: "حفظ جلسات التحليل في Hub.",
  },
  {
    key: "factory_hub:project_autosave:read",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "قراءة مسودة مشروع جديد",
    labelEn: "Read new project autosave",
    descriptionAr: "قراءة مسودة معالج المشروع.",
  },
  {
    key: "factory_hub:project_autosave:write",
    module: "factory_hub",
    moduleLabelAr: "مصنع البيانات (Hub)",
    labelAr: "كتابة مسودة مشروع جديد",
    labelEn: "Write new project autosave",
    descriptionAr: "حفظ مسودة معالج المشروع.",
  },
  {
    key: "employees:view",
    module: "directory",
    moduleLabelAr: "الدليل التنظيمي",
    labelAr: "عرض الموظفين",
    labelEn: "View employees",
    descriptionAr: "استعراض قائمة الموظفين والأقسام.",
  },
  {
    key: "employees:export",
    module: "directory",
    moduleLabelAr: "الدليل التنظيمي",
    labelAr: "تصدير بيانات الموظفين",
    labelEn: "Export employees",
    descriptionAr: "تصدير CSV للموظفين.",
  },
  {
    key: "capacity:view",
    module: "directory",
    moduleLabelAr: "الدليل التنظيمي",
    labelAr: "عرض السعة والمهام",
    labelEn: "View capacity & tasks",
    descriptionAr: "قراءة جداول السعة والمصانع والأقسام.",
  },
  {
    key: "capacity:write",
    module: "directory",
    moduleLabelAr: "الدليل التنظيمي",
    labelAr: "تعديل السعة والمهام",
    labelEn: "Edit capacity & tasks",
    descriptionAr: "تعديل تعريفات السعة والمهام.",
  },
  {
    key: "directory:departments:view",
    module: "directory",
    moduleLabelAr: "الدليل التنظيمي",
    labelAr: "عرض صفحة الأقسام والهيكل",
    labelEn: "View departments overview",
    descriptionAr: "صفحة أقسام الخشب والمعادن وجداول السعة.",
  },
  {
    key: "import_export:import",
    module: "integration",
    moduleLabelAr: "التكامل",
    labelAr: "استيراد ملفات",
    labelEn: "Import data",
    descriptionAr: "استيراد Excel وملفات البيانات.",
  },
  {
    key: "import_export:export",
    module: "integration",
    moduleLabelAr: "التكامل",
    labelAr: "تصدير ملفات",
    labelEn: "Export data",
    descriptionAr: "تصدير البيانات من النظام.",
  },
  {
    key: "audit:view",
    module: "audit",
    moduleLabelAr: "التدقيق",
    labelAr: "عرض سجل التحركات",
    labelEn: "View audit log",
    descriptionAr: "قراءة أحداث التدقيق والمسارات.",
  },
  {
    key: "audit:export",
    module: "audit",
    moduleLabelAr: "التدقيق",
    labelAr: "تصدير سجل التدقيق",
    labelEn: "Export audit log",
    descriptionAr: "تصدير السجل للمراجعة الخارجية.",
  },
  {
    key: "performance:departments:view",
    module: "analytics",
    moduleLabelAr: "الأداء",
    labelAr: "عرض لوحة أداء الأقسام",
    labelEn: "View department performance",
    descriptionAr: "لوحة مقاييس وأعباء الأقسام.",
  },
  {
    key: "performance:people:view",
    module: "analytics",
    moduleLabelAr: "الأداء",
    labelAr: "عرض لوحة أداء الأفراد",
    labelEn: "View people performance",
    descriptionAr: "مقارنة الأفراد ضمن النطاق المسموح.",
  },
  {
    key: "admin:permissions:view",
    module: "admin",
    moduleLabelAr: "إدارة النظام",
    labelAr: "عرض لوحة توزيع الصلاحيات",
    labelEn: "View permissions admin",
    descriptionAr: "الوصول لشاشة مصفوفة الصلاحيات.",
  },
  {
    key: "admin:permissions:manage",
    module: "admin",
    moduleLabelAr: "إدارة النظام",
    labelAr: "توزيع الصلاحيات على الأدوار والمستخدمين",
    labelEn: "Manage roles & user assignments",
    descriptionAr: "تعديل ربط الأدوار بالصلاحيات وتعيين الأدوار للمستخدمين.",
  },
  {
    key: "admin:users:manage",
    module: "admin",
    moduleLabelAr: "إدارة النظام",
    labelAr: "إدارة حسابات المستخدمين",
    labelEn: "Manage user accounts",
    descriptionAr: "إنشاء وتعطيل حسابات المستخدمين عند تفعيل المصادقة.",
  },
];

/** مفاتيح معرفة برمجياً */
export const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.map((p) => p.key);

/** أدوار افتراضية مع وصف عربي */
export const ROLE_PRESETS: {
  id: string;
  slug: string;
  labelAr: string;
  labelEn: string;
  permissionKeys: readonly string[];
}[] = [
  {
    id: "role_super_admin",
    slug: "super_admin",
    labelAr: "مدير النظام الأعلى",
    labelEn: "Super administrator",
    permissionKeys: ALL_PERMISSION_KEYS,
  },
  {
    id: "role_factory_admin",
    slug: "factory_admin",
    labelAr: "مدير مصنع",
    labelEn: "Factory administrator",
    permissionKeys: ALL_PERMISSION_KEYS.filter(
      (k) => k !== "admin:users:manage" && k !== "admin:permissions:manage",
    ),
  },
  {
    id: "role_department_lead",
    slug: "department_lead",
    labelAr: "رئيس قسم",
    labelEn: "Department lead",
    permissionKeys: [
      "dashboard:view",
      "dashboard:widgets",
      "production:hub:view",
      "orders:wood:view",
      "orders:wood:write",
      "orders:metal:view",
      "daily:wood:view",
      "daily:wood:write",
      "daily:metal:view",
      "daily:metal:write",
      "projects:new:view",
      "projects:new:write",
      "projects:wo_analysis:view",
      "projects:wo_analysis:write",
      "planning:view",
      "planning:write",
      "analytics:multi:view",
      "analytics:wood:view",
      "analytics:metal:view",
      "project_analytics:view",
      "equipment:view",
      "about:view",
      "factory_hub:wood:read",
      "factory_hub:wood:write",
      "factory_hub:reference:read",
      "factory_hub:analysis:read",
      "factory_hub:analysis:write",
      "factory_hub:project_autosave:read",
      "factory_hub:project_autosave:write",
      "employees:view",
      "capacity:view",
      "import_export:export",
      "audit:view",
      "directory:departments:view",
      "performance:departments:view",
      "performance:people:view",
      "entity_notes:read",
      "entity_notes:write",
    ],
  },
  {
    id: "role_operator",
    slug: "operator",
    labelAr: "مشغّل / فني إنتاج",
    labelEn: "Operator",
    permissionKeys: [
      "dashboard:view",
      "production:hub:view",
      "orders:wood:view",
      "orders:wood:write",
      "orders:metal:view",
      "daily:wood:view",
      "daily:wood:write",
      "daily:metal:view",
      "daily:metal:write",
      "equipment:view",
      "about:view",
      "factory_hub:wood:read",
      "factory_hub:wood:write",
      "factory_hub:project_autosave:read",
      "factory_hub:project_autosave:write",
      "directory:departments:view",
      "performance:departments:view",
      "performance:people:view",
      "entity_notes:read",
      "entity_notes:write",
    ],
  },
  {
    id: "role_viewer",
    slug: "viewer",
    labelAr: "مطلع فقط",
    labelEn: "Viewer",
    permissionKeys: ALL_PERMISSION_KEYS.filter(
      (k) =>
        (k.endsWith(":view") || k.endsWith(":read")) &&
        !k.startsWith("admin:") &&
        !k.includes(":write") &&
        !k.includes(":export") &&
        !k.includes(":import"),
    ),
  },
];

export function permissionKeyToStableId(key: string): string {
  return `perm_${key.replace(/[^a-zA-Z0-9]+/g, "_")}`;
}
